const DEV = false;

const LNG = {
    "setting": "设置",
    "language": "语言",
    "return2Gallery": "返回画廊",
    "resizeCanvas": "缩放画布",
    "return": "返回",
    "save": "保存",
    "cancel": "取消",
    "confirm": "确认",
    "saveAsPNG": "导出PNG",
    "flipX": "翻转X轴",
    "flipY": "翻转Y轴",
    "scaleUpUI": "放大界面",
    "scaleDownUI": "缩小界面",
    "group": "建组",
    "delete": "删除",
    "history": "历史",
    "clearHistory": "清空历史",
    "rename": "重命名",
    "lockALpha": "锁定透明度",
    "unlockAlpha": "解锁透明度",
    "stampRotFollow": "跟随运笔",
    "intensity": "强度",
    "stepNum": "步数",
    "blur": "模糊",
    "number": "个数",
    "advanced": "高级",
    "name": "名称",
    "duplicate": "复制",
    "iterate": "迭代",
    "copy": "复制",
    "applyToActLayer": "应用",
    "createNewLayer": "新建图层",
    "resizeProjectToFit": "缩放以适应",
    "copyFromCanvas": "从画布复制",
    "stablization": "稳定",
    "spread": "分布",
    "spacing": "间隔",
    "startTip": "开始收尖",
    "endTip": "结束收尖",
    "rotate": "旋转",
    "grain": "纹理",
    "press2size": "尺寸 - 压感",
    "press2Flow": "流量 - 压感",
    "brushSetting": "画笔设置",
    "stamp": "印章",
    "debug": "调试",
    "showActLayer": "显示当前图层",
    "copyToDocker": "复制到图库",
    "cancelPreview": "取消预览",
    "toggleImgDocker": "显示/隐藏图库",
    "maskToolHint": "仅普通、橡皮、柳叶笔笔刷支持遮罩模式",
    "quitMask": "退出",
    "applyMask": "应用",
    "resetMask": "重置遮罩",
    "moveMasked": "移动选中",
    "rembg": "背景移除",
    "autoGen": "自动生成",
    "requestFailed": "请求失败：",
    "startGenerate": "生成",
    "typePosPromptHere": "正面提示词",
    "typeNegPromptHere": "反面提示词",
    "generating": "生成中",
    "queueing": "上传中",
    "pleaseWait": "请稍等",
    "backup": "备份",
    "scale": "缩放",
    "create": "创建",
    "genPreset": "预设",
    "gen9": "90%",
    "gen8": "80%",
    "gen7": "70%",
    "gen6": "60%",
    "gen5": "50%",
    "gen4": "40%",
    "gen3": "30%",
    "gen2": "20%",
    "gen1": "10%",
    "batchNum": "次数",
    "batch": "次",
    "previewing": "预览中",

    "dropToOpenProject": "以图像创建项目",

    "generalMode": "通用",
    "lineArtMode": "线稿",
    "controlMode": "控制",
    "maskMode": "遮罩特化",
    "structual": "结构",
    "SemanticMode": "语义引导",

    "errorReceivingImg": "接收图片时出错",
    "errorImgTooLarge": "图片大小限制为4K",
    "errorImgTooSmall": "图片长宽不得小于16px",
    "canvasStepAdjust": "图片长宽调整为4的倍数",
    "imageNotReady": "图片未加载",

    "saveBubble": "保存词条：",
    "positive": "正面",
    "negative": "负面",
    "library": "图库",
    "community": "社区",
    "noOutput": "无输出图像",

    "threshold": "阈值",
    "boundary": "边界",

    "backspace": "退格",
    "zero": "归零",
    "reset": "重置",

    "gallery": "画廊",
    "dragDropOrImport": "拖拽或导入",

}